version: "2"
linters:
  default: all
  disable:
    - wsl # deprecated (since v2.2.0)
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/aws/aws-sdk-go-v2/aws
            - github.com/aws/aws-sdk-go-v2/config
            - github.com/aws/aws-sdk-go-v2/credentials
            - github.com/aws/aws-sdk-go-v2/service/sts
            - github.com/hashicorp/hcl/v2
            - github.com/hashicorp/hcl/v2/hclparse
            - github.com/hashicorp/hcl/v2/hclsimple
            - github.com/wakeful/trick/internal/parser
            - github.com/zclconf/go-cty/cty
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: disable
    rules:
      - linters:
          - err113
          - exhaustruct
          - funlen
          - varnamelen
        path: _test.go
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
