repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.28
    hooks:
      - id: shellcheck
      - id: gofmt
  - repo: local
    hooks:
      - id: addlicense
        name: Add License
        entry: addlicense -c 'variHQ OÜ' -l 'BSD-3-Clause' -s=only
        language: system
        types: [ file ]
        exclude: '\.(hcl|yaml|yml)$'
